version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:8.11

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install nodejs dependencies
          command: npm install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "venv"

      - persist_to_workspace:
          root: ~/code
          paths:
            - .

  unit_test:
    working_directory: ~/code
    docker:
      - image: circleci/node:8.11

    steps:
      - attach_workspace:
          at: ~/code

      - run:
          name: Run unit tests
          command: npm test

workflows:
  version: 2.1
  build-test:
    jobs:
      - build:

      - unit_test:
          requires:
            - build